spring.datasource.url=${H2_URL}
spring.datasource.driver-class-name=${H2_DRIVER}
spring.datasource.username=${H2_USERNAME}
spring.datasource.password=${H2_PASSWORD}
spring.jpa.database-platform=${H2_DIALECT}
spring.jpa.hibernate.ddl-auto=${H2_DDL_AUTO}
spring.jpa.show-sql=${H2_SHOW_SQL}

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
